version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9  # Update the Python version as needed
  node-executor:
    docker:
      - image: circleci/node:16  # Update the Node.js version as needed

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.9"  # Keep your existing Python version if necessary
    steps:
      - checkout
      - run:
          name: Run Add Script
          command: python3 backend/add.py

  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.9"  # Keep your existing Python version if necessary
    steps:
      - checkout
      - run:
          name: Run Add Test Script
          command: python3 backend/add_test.py



  install-frontend:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Node.js Dependencies
          command: |
            cd frontend  # Update this path if your frontend folder name is different
            npm install

  deploy-to-ec2:
    docker:
      - image: circleci/python:3.9
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:UrS2gCQnKvY88GLdu3/sBG48StJW1gN/iG0+TLsQ0Lo"  # Replace with the correct fingerprint from CircleCI settings
      - run:
          name: Deploy to EC2
          command: |
              ssh -o StrictHostKeyChecking=no ubuntu@<13.250.103.232> \<< 'EOF'
              # Ensure the deployment folder exists
              mkdir -p /home/ec2-user/Desktop/HiveTalk
              # Navigate to the deployment folder
              cd /home/ec2-user/Desktop/HiveTalk
              git pull origin circleci-project-setup      # Pull the latest code, adjust the branch as needed
              source venv/bin/activate  # Activate the backend virtual environment
              pip install -r backend/requirements.txt
              cd frontend
              npm install
              npm run build             # Build the frontend if necessary
              # Restart services as needed
              sudo systemctl restart my-backend-service  # Replace with your actual service restart command
            EOF

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - install-frontend
      - deploy-to-ec2:
          requires:
            - install-frontend
