version: 2.1

executors:
  ubuntu-executor:
    docker:
      - image: circleci/python:3.9  # Ubuntu-based image with Python installed

jobs:
  build-backend:
    executor: ubuntu-executor
    steps:
      - checkout
      - run:
          name: Install Backend Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install fastapi "uvicorn[standard]" requests
            pip freeze > backend/requirements.txt

      - run:
          name: Run Backend Script
          command: |
            source venv/bin/activate
            python3 backend/add.py

  test-backend:
    executor: ubuntu-executor
    steps:
      - checkout
      - run:
          name: Run Backend Tests
          command: |
            python3 backend/add_test.py

  build-frontend:
    docker:
      - image: circleci/node:16  # Node.js version can be adjusted as needed
    steps:
      - checkout
      - run:
          name: Install Node.js Dependencies
          command: |
            cd frontend
            npm install
      - run:
          name: Build React App
          command: |
            cd frontend
            npm run build

  deploy:
    executor: ubuntu-executor
    steps:
      - checkout
      - run:
          name: Install Deployment Tools
          command: |
            sudo apt-get update
            sudo apt-get install -y rsync ssh awscli

      - add_ssh_keys:
          fingerprints:
            - "SHA256:r05suI0QYBEYtr9BPa2LM9ybLpnzWVm9uSfmad8FwlY"  # Replace with your SSH fingerprint

      - run:
          name: Deploy Backend to EC2
          command: |
            # Define variables
            EC2_USER=ubuntu 
            EC2_HOST=3.25.58.202
            LOCAL_BACKEND_DIR=/Users/aungkhantsoe/Desktop/pythonjs_chat/backend
            REMOTE_BACKEND_DIR=/home/ubuntu/backend

            # Ensure the backend directory exists on EC2
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST \<< EOF
              mkdir -p $REMOTE_BACKEND_DIR
            EOF 
            
            # Deploy backend code
            rsync -avz -e "ssh -o StrictHostKeyChecking=no" $LOCAL_BACKEND_DIR/ $EC2_USER@$EC2_HOST:$REMOTE_BACKEND_DIR

            # Install backend dependencies on EC2
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST \<< EOF
              cd $REMOTE_BACKEND_DIR
              python3 -m venv venv
              source venv/bin/activate
              pip install --upgrade pip
              pip install -r requirements.txt
              # Add command to start the backend service if necessary
            EOF

      - run:
          name: Deploy Frontend to EC2
          command: |
            # Define variables
            LOCAL_FRONTEND_DIR=/Users/aungkhantsoe/Desktop/pythonjs_chat/frontend/dist
            REMOTE_FRONTEND_DIR=/home/ubuntu/frontend

            # Deploy frontend build
            rsync -avz -e "ssh -o StrictHostKeyChecking=no" $LOCAL_FRONTEND_DIR/ $EC2_USER@$EC2_HOST:$REMOTE_FRONTEND_DIR

            # Optional: Restart services on EC2
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST \<< EOF
              echo "Deployment completed."
              # Add commands to restart backend and frontend services if necessary
            EOF

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-backend
      - test-backend:
          requires:
            - build-backend
      - build-frontend
      - deploy:
          requires:
            - test-backend
            - build-frontend
